# Generated by Django 6.0.7 on 2026-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=30)),
                ("platform_account_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("affected_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_logs",
            },
        ),
        migrations.CreateModel(
            name="DashboardDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_date", models.DateField()),
                ("platform_id", models.IntegerField()),
                ("order_count", models.IntegerField(default=0)),
                ("gross_sales", models.BigIntegerField(default=0)),
                ("total_cost", models.BigIntegerField(default=0)),
                ("est_margin", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_daily_stats",
                "unique_together": {("stat_date", "platform_id")},
            },
        ),
    ]
