# Generated by Django 6.0.7 on 2026-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "platforms",
            },
        ),
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_account_id", models.BigIntegerField()),
                ("key_type", models.CharField(max_length=30)),
                ("value_encrypted", models.BinaryField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_credentials",
            },
        ),
        migrations.CreateModel(
            name="PlatformFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_id", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("fee_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("effective_from", models.DateField()),
            ],
            options={
                "db_table": "platform_fees",
            },
        ),
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_id", models.IntegerField()),
                ("account_name", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_accounts",
                "unique_together": {("platform_id", "account_name")},
            },
        ),
    ]
