# Generated by Django 6.0.7 on 2026-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField()),
                ("listing_id", models.BigIntegerField(blank=True, null=True)),
                ("source_product_id", models.BigIntegerField(blank=True, null=True)),
                ("product_name", models.CharField(max_length=500)),
                (
                    "option_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.IntegerField()),
                ("unit_sale_price", models.IntegerField()),
                ("unit_cost_price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_item_id", models.BigIntegerField()),
                ("supplier_platform_id", models.IntegerField()),
                (
                    "supplier_order_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=30)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_order_id", models.BigIntegerField()),
                (
                    "courier_code",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "tracking_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="ready", max_length=30)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_market", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "shipments",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_account_id", models.BigIntegerField()),
                ("market_order_no", models.CharField(max_length=100)),
                ("order_status", models.CharField(max_length=30)),
                ("buyer_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "receiver_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "receiver_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("receiver_address", models.TextField(blank=True, null=True)),
                ("total_amount", models.IntegerField()),
                ("raw_payload", models.JSONField()),
                ("ordered_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "orders",
                "unique_together": {("platform_account_id", "market_order_no")},
            },
        ),
    ]
