# Generated by Django 6.0.7 on 2026-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.BigIntegerField()),
                ("source_option_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "market_option_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sale_price", models.IntegerField()),
            ],
            options={
                "db_table": "listing_options",
            },
        ),
        migrations.CreateModel(
            name="SourceProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_product_id", models.BigIntegerField()),
                ("option_name", models.CharField(max_length=200)),
                ("cost_price", models.IntegerField(blank=True, null=True)),
                ("stock_qty", models.IntegerField(default=0)),
                (
                    "supplier_option_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "source_product_options",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_product_id", models.BigIntegerField()),
                ("platform_account_id", models.BigIntegerField()),
                (
                    "market_product_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sale_price", models.IntegerField()),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "margin_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("listed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "listings",
                "unique_together": {("platform_account_id", "market_product_id")},
            },
        ),
        migrations.CreateModel(
            name="SourceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_platform_id", models.IntegerField()),
                ("supplier_product_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=500)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("cost_price", models.IntegerField()),
                ("stock_qty", models.IntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=20)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "source_products",
                "unique_together": {("supplier_platform_id", "supplier_product_code")},
            },
        ),
    ]
